version: "3.3"


services:
  server:
    container_name: base-server
    build:
      context: .
      args:
        - MODE=local
        - CHEATS=true
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    restart: always
    depends_on:
      - server-db
    networks:
      - bet-overlord-service_net
      - rng-service_net
      - net
  server-db:
    container_name: base-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    networks:
      - net
  prom:
    container_name: stonesofmagic-prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - server
    networks:
      - net
  grafana:
    container_name: stonesofmagic-grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prom
    networks:
      - net

networks:
  net:
    driver: bridge
  bet-overlord-service_net:
    external: true
  rng-service_net:
    external: true

volumes:
  prometheus_data:
    driver: local
  grafana-storage:
    driver: local